### ISSUE TITLE
err write ECANCELED

### ISSUE THREAD

**Issue by oky1** [965283058/koa-video#1]
Sometimes when i starting or refreshing of localhost i get this err:
Error: write ECANCELED
      at _errnoException (util.js:1022:11)
      at WriteWrap.afterWrite (net.js:867:14)

it's probably node.js err, but if you have any solutions .... it's will be great
node v8.9.4
I think need to stop stream when connection is lost and send: stream(null) or input.close() or stream.destroy();

**Comment by 965283058** [comment]
fix this bug,Thanks
